---
- name: install aptitude
  apt:
    name: "aptitude"
    state: latest
    update_cache: yes
- name: update packages
  apt:
    name: "*"
    state: latest
- name: install netstat
  apt:
    name: "net-tools"
    state: latest
- name: install htop
  apt:
    name: "htop"
    state: latest
- name: install vim
  apt:
    name: "vim"
    state: latest
- name: install git
  apt:
    name: "git"
    state: latest
- name: install sudo
  apt:
    name: "sudo"
    state: latest
- name: Install tree
  apt:
    name: "tree"
    state: latest